### ISSUE TITLE
Beautiful soup problem

### ISSUE THREAD

**Issue by flschiavoni** [flschiavoni/harpia#89]
Traceback (most recent call last):
  File "/usr/local/bin/harpia", line 4, in <module>
    __import__('pkg_resources').run_script('harpia==1.0', 'harpia')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1504, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/harpia-1.0-py2.7.egg/EGG-INFO/scripts/harpia", line 49, in <module>
    main(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/harpia-1.0-py2.7.egg/EGG-INFO/scripts/harpia", line 31, in main
    win = MainWindow()
  File "/usr/local/lib/python2.7/dist-packages/harpia-1.0-py2.7.egg/harpia/GUI/mainwindow.py", line 22, in __init__
    System()
  File "/usr/local/lib/python2.7/dist-packages/harpia-1.0-py2.7.egg/harpia/system.py", line 163, in __new__
    System.instance = System.__Singleton()
  File "/usr/local/lib/python2.7/dist-packages/harpia-1.0-py2.7.egg/harpia/system.py", line 68, in __init__
    self.__load()
  File "/usr/local/lib/python2.7/dist-packages/harpia-1.0-py2.7.egg/harpia/system.py", line 78, in __load
    PreferencesControl(self.properties).load()
  File "/usr/local/lib/python2.7/dist-packages/harpia-1.0-py2.7.egg/harpia/control/preferencescontrol.py", line 24, in load
    xml_loader = XMLParser(file_name)
  File "/usr/local/lib/python2.7/dist-packages/harpia-1.0-py2.7.egg/harpia/utils/XMLUtils.py", line 20, in __init__
    self.__dict__['parsedXML'] = BeautifulSoup(open(source), "xml")
  File "/usr/local/lib/python2.7/dist-packages/bs4/__init__.py", line 165, in __init__
    % ",".join(features))
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: xml. Do you need to install a parser library?

**Comment by flschiavoni** [comment]
sudo apt-get install python-lxml
